language: cpp
addons:
  apt:
    packages:
    - "python3"
    - "python3-pip"
compiler:
- gcc
install:
# Upgrade GCC
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.9
- sudo apt-get install python3
- sudo apt-get install python3-pip
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9

# Install conan
- pip3 install conan
# Automatic detection of your arch, compiler, etc.
- conan user

script:
# Download dependencies, build, test and create package
- conan create . elvircrn/nesemu


notifications:
  email: false

